export const FEED_PAGE_TABS = [
  { key: "all", title: "全部" },
  { key: "course", title: "公开课" },
  { key: "game", title: "游戏" },
  { key: "anime", title: "二次元" },
  { key: "music", title: "音乐" },
  { key: "movie", title: "影视" },
  { key: "food", title: "美食" },
  { key: "knowledge", title: "知识" },
  { key: "shortPlay", title: "小剧场" },
  { key: "vlog", title: "生活vlog" },
  { key: "sports", title: "体育" },
  { key: "travel", title: "旅行" },
  { key: "parenting", title: "亲子" },
  { key: "animal", title: "动物" },
  { key: "agriculture", title: "三农" },
  { key: "car", title: "汽车" },
  { key: "beauty", title: "美妆穿搭" },
]